### ISSUE TITLE
Github flow. Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by cmoulliard** [ippie52/markdown_code_embed_action#7]
## Issue

When the following workflow 
```
name: Embed code in README

on:
  push:
    branches:
      - main

jobs:
  embed-code:
    runs-on: ubuntu-latest
    permissions:
      contents: write # release changes require contents write
    steps:
      - uses: actions/checkout@v2

      - name: Markdown Code Embed
        uses: ippie52/markdown_code_embed_action@2.0.1
        with:
          args: '-q'
```
runs on my project than the github flow exits
```

Run ./markdown_code_embed/mdce.py -q
  ./markdown_code_embed/mdce.py -q
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Files tracked by Git modified on this run:
	/home/runner/work/pipeline-dsl-builder/pipeline-dsl-builder/README.md
Error: Process completed with exit code 1.
```

![Screenshot 2024-08-07 at 15 33 20](https://github.com/user-attachments/assets/bc094909-7f9b-4988-9049-41d94b9ce83a)

Remark: I can run on the same README.md file the command `mdce` locally on my machine
```
python -m mdce -d ../..
Checking /Users/cmoullia/code/ch007m/pipeline-dsl-builder/builder
Found file: /Users/cmoullia/code/ch007m/pipeline-dsl-builder/builder/README.md
Parsing: [100%] /Users/cmoullia/code/ch007m/pipeline-dsl-builder/builder/README.md

Files updated on this run:
        /Users/cmoullia/code/ch007m/pipeline-dsl-builder/builder/README.md
Files tracked by Git modified on this run:
        /Users/cmoullia/code/ch007m/pipeline-dsl-builder/builder/README.md
```
